name: wimpillay_main
description: Proyecto con login de Google y Firebase integrado.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # ðŸ”¥ Firebase base
  firebase_core: ^3.3.0
  # ðŸ”‘ AutenticaciÃ³n con Firebase
  firebase_auth: ^5.2.0
  # â˜ï¸ Base de datos Firestore
  cloud_firestore: ^5.2.0
  # ðŸ”µ Login con Google
  google_sign_in: ^6.2.1

  qr_flutter: ^4.1.0

  intl: ^0.18.1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    
flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"